# Recommend 서비스 설정 (EKS 환경 기본)
server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: recommend

  datasource:
    url: jdbc:postgresql://${AURORA_RECOMMEND_ENDPOINT}:5432/mapzip_recommend
    username: mapzip-recommend-${TERRAFORM_WORKSPACE:dev}
    password: ${DB_PASSWORD} 
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate 
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:                 
      host: ${ELASTICACHE_RECOMMEND_ENDPOINT}
      port: 6379
      ssl:
        enabled: true      
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  cloud:
    kubernetes:
      discovery:
        enabled: true

eureka:
  client:
    enabled: false

# Kafka 
spring:
  kafka:
    bootstrap-servers: ${MSK_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: recommend-service
      auto-offset-reset: earliest


# gRPC
grpc:
  server:
    port: 9092
    reflection-service-enabled: true

# 다른 서비스 gRPC 목적지(DNS로!)
#clients:
#  review:
#    host: 
#    port :
#  schedule:
#    host: 
#    port: 

# 외부 API
external:
  api:
    kakao:
      url: https://dapi.kakao.com
      key: ${KAKAO_API_KEY}   
    tmap:
      url: https://apis.openapi.sk.com
      key: ${TMAP_API_KEY}   

# Actuator/Prometheus 
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    export:
      prometheus:
        enabled: true


