# Review Service Configuration - Production Profile
server:
  port: 8080

# AWS Configuration for Production
aws:
  region: ap-northeast-2
  dynamodb:
    table-name: reviews
    # Production DynamoDB endpoint will be resolved automatically
  s3:
    bucket: mapzip-images
    region: ap-northeast-2

# Google Cloud Vision API (Production)
google:
  cloud:
    vision:
      api-key: '{cipher}암호화된_PROD_API_키'

# Production logging - less verbose
logging:
  level:
    com.mapzip.review: INFO
    software.amazon.awssdk: WARN
    com.google.cloud: WARN
    org.springframework.cloud.config: INFO
    root: WARN

# Review Service Production Settings
review:
  ocr:
    confidence-threshold: 0.7  # Higher threshold for production
    max-retry-attempts: 3
  image:
    max-file-size: 10MB
    allowed-types: image/jpeg,image/png,image/jpg
  pagination:
    default-size: 20
    max-size: 100

# Production optimizations
spring:
  jackson:
    default-property-inclusion: NON_NULL
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

# Production management settings
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true
        step: 60s