# Review Service Configuration - Development Profile
server:
  port: 8080

# AWS Configuration for Development
aws:
  region: ap-northeast-2
  dynamodb:
    table-name: reviews-dev
    endpoint: http://localhost:8000  # For local DynamoDB testing
  s3:
    bucket: mapzip-images-dev
    region: ap-northeast-2

# Google Cloud Vision API (Development)
google:
  cloud:
    vision:
      api-key: ${GOOGLE_CLOUD_VISION_API_KEY_DEV}

# Development specific logging
logging:
  level:
    com.mapzip.review: DEBUG
    software.amazon.awssdk: DEBUG
    com.google.cloud: DEBUG
    org.springframework.cloud.config: DEBUG
    org.springframework.web: DEBUG

# Review Service Development Settings
review:
  ocr:
    confidence-threshold: 0.5  # Lower threshold for dev testing
    max-retry-attempts: 1
  image:
    max-file-size: 5MB  # Smaller for dev
    allowed-types: image/jpeg,image/png,image/jpg,image/gif
  pagination:
    default-size: 10
    max-size: 50

# Development database settings
spring:
  jackson:
    default-property-inclusion: NON_NULL
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB