# Schedule 서비스 설정 (EKS 환경 기본)

server:
  port: ${SERVER_PORT:8084}

spring:
  application:
    name: schedule
    
  # Aurora PostgreSQL 연결 (schedule 클러스터) - 환경변수 필수
  datasource:
    url: jdbc:postgresql://mapzip-dev-schedule-db.cluster-c3qme6c6e7fj.ap-northeast-2.rds.amazonaws.com:5432/schedule_db
    username: mapzip
    password: '{cipher}8e1486a57e6c448a6bf9973cace90c244c4e548d54ba9e655fa183d940c8e8f3'
    driver-class-name: org.postgresql.Driver
    
  # JPA 설정 (운영 환경 기준)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Kubernetes 서비스 디스커버리 활성화
  cloud:
    kubernetes:
      discovery:
        enabled: true

# gRPC 서버 설정
grpc:
  server:
    port: 9090
    reflection-service-enabled: true
  client:
    kakao-api-service:
      address: static://localhost:9090
      negotiation-type: plaintext

# 로깅 설정
logging:
  level:
    com.mapzip.schedule: DEBUG

# Health check and metrics
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

# 스케줄링 관련 설정
scheduling:
  enabled: ${SCHEDULING_ENABLED:true}
  pool-size: ${SCHEDULING_POOL_SIZE:10}

# Eureka 비활성화
eureka:
  client:
    enabled: false

# AWS 자격 증명 설정
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ${AWS_REGION:ap-northeast-2}

# 외부 API 설정
external:
  api:
    tmap:
      url: https://apis.openapi.sk.com
      key: '{cipher}f78b10e7eb93c8dd7164c79d8b07799aae13b71043f5473206b3e8fc44980e8c68af082ea0ceeda1bc128040a5677f64501ceb845d13c23a761de3101c7b407b'
    kakao:
      url: https://dapi.kakao.com
      key: '{cipher}b3c8d5625fc982f63c90101890b2e0dcbe7a48c73f401b57fdc74474569d12a9f5f992bea8d8da16380ec1f3da05ec3174c1b0c2d364f73aa9c71db86ee6b3d8'

# 개발 환경용 인증 설정
auth:
  enabled: false
