# Gateway 서비스 설정

server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth
          predicates:
            - Path=/api/auth/**
        - id: review-service
          uri: lb://review
          predicates:
            - Path=/api/reviews/**
        - id: recommend-service
          uri: lb://recommend
          predicates:
            - Path=/api/recommend/**
        - id: schedule-service
          uri: lb://schedule
          predicates:
            - Path=/api/schedule/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
