
# services:
#   envoy:
#     image: envoyproxy/envoy:v1.29-latest
#     container_name: envoy-proxy
#     volumes:
#       - ./envoy.yaml:/etc/envoy/envoy.yaml
#       - ./backend/schedule/schedule_proto.pb:/etc/envoy/proto.pb
#     ports:
#       - "8000:8000"
#       - "9901:9901"
#     command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml --service-cluster schedule-proxy

#   valkey:
#     image: valkey/valkey:7.2-alpine
#     container_name: valkey
#     ports:
#       - "6379:6379"

  