# Gateway 서비스 설정 (EKS 환경)

server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: gateway
  cloud:
    kubernetes:
      discovery:
        enabled: true        
        all-namespaces: false

# Eureka 비활성화 (EKS에서는 Kubernetes 사용)
eureka:
  client:
    enabled: false
