apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: mapzip
  labels:
    app: config-server
    version: v1
spec:
  replicas: 2  # 고가용성을 위해 2개 인스턴스
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
        version: v1
    spec:
      containers:
      - name: config-server
        image: ${ECR_REGISTRY}/mapzip/config-server:${IMAGE_TAG}
        ports:
        - containerPort: 8888
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: JAVA_OPTS
          value: "-Xmx512m -Xms256m"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8888
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8888
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      imagePullSecrets:
      - name: ecr-secret
