apiVersion: v1
kind: Service
metadata:
  name: config
  namespace: platform
  labels:
    app: config
spec:
  type: ClusterIP
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
    name: http
  selector:
    app: config
---
# 외부 접근을 위한 LoadBalancer (선택사항)
apiVersion: v1
kind: Service
metadata:
  name: config-external
  namespace: platform
  labels:
    app: config
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8888
    protocol: TCP
    name: http
  selector:
    app: config
