apiVersion: v1
kind: Service
metadata:
  name: config-server-service
  namespace: mapzip
  labels:
    app: config-server
spec:
  type: ClusterIP
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
    name: http
  selector:
    app: config-server
---
# 외부 접근을 위한 LoadBalancer (선택사항)
apiVersion: v1
kind: Service
metadata:
  name: config-server-external
  namespace: mapzip
  labels:
    app: config-server
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8888
    protocol: TCP
    name: http
  selector:
    app: config-server
