# Schedule 서비스 설정 (EKS 환경 기본)

server:
  port: ${SERVER_PORT:8084}

spring:
  application:
    name: schedule
    
  # Aurora PostgreSQL 연결 (schedule 클러스터) - 환경변수 필수
  datasource:
    url: jdbc:postgresql://${AURORA_SCHEDULE_ENDPOINT}:5432/mapzip_schedule
    username: mapzip-schedule-${TERRAFORM_WORKSPACE:dev}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    
  # JPA 설정 (운영 환경 기준)
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# 스케줄링 관련 설정
scheduling:
  enabled: ${SCHEDULING_ENABLED:true}
  pool-size: ${SCHEDULING_POOL_SIZE:10}

# Kubernetes 서비스 디스커버리 활성화
spring:
  cloud:
    kubernetes:
      discovery:
        enabled: true

# Eureka 비활성화
eureka:
  client:
    enabled: false
