# Auth 서비스 설정 (EKS 환경 기본)

server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: auth
    
  # ElastiCache valkey 연결 (auth-cache 클러스터) - 환경변수 필수
  data:
    valkey:
      host: ${ELASTICACHE_AUTH_ENDPOINT}
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  # Kubernetes 서비스 디스커버리 활성화
  cloud:
    kubernetes:
      discovery:
        enabled: true

# Eureka 비활성화
eureka:
  client:
    enabled: false
