# Auth 서비스 설정

server:
  port: 8081

spring:
  application:
    name: auth
  datasource:
    url: jdbc:mysql://localhost:3306/mapzip_auth
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# JWT 설정 (예시)
jwt:
  secret: mapzip-secret-key
  expiration: 86400000  # 24시간
