spring:
  application:
    name: review
  config:
    import: optional:configserver:http://config.service-platform.svc.cluster.local:8888
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

# HTTP 서버 설정 
server:
  port: ${SERVER_PORT:8080}

# gRPC 서버 설정
grpc:
  server:
    port: ${GRPC_SERVER_PORT:50051}
    reflection-service-enabled: true
  client:
    GLOBAL:
      negotiation-type: plaintext

# Actuator 설정 (헬스체크 + 모니터링)
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    prometheus:
      enabled: true
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      service: review
      environment: ${spring.profiles.active:dev}
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

# 로깅 설정
logging:
  level:
    com.mapzip.review: ${LOG_LEVEL:INFO}
    org.springframework.cache: ${LOG_LEVEL:INFO}
    org.springframework.data.redis: ${LOG_LEVEL:INFO}
    root: INFO