# Review Service Configuration - Default Profile
server:
  port: 8080

# gRPC Configuration  
grpc:
  server:
    port: 50051
  client:
    GLOBAL:
      negotiation-type: plaintext

# AWS Configuration
aws:
  region: ap-northeast-2
  credentials:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
  dynamodb:
    table-name: reviews
    endpoint: ${DYNAMODB_ENDPOINT:}
  s3:
    bucket: mapzip-images
    region: ap-northeast-2

# Google Cloud Vision API
google:
  cloud:
    vision:
      api-key: ${GOOGLE_CLOUD_VISION_API_KEY}

# Database Connection Pool
spring:
  main:
    allow-bean-definition-overriding: true
  
# Logging Configuration
logging:
  level:
    com.mapzip.review: DEBUG
    software.amazon.awssdk: INFO
    com.google.cloud: INFO
    org.springframework.cloud.config: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management & Health Check
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Review Service Specific Settings
review:
  ocr:
    confidence-threshold: 0.6
    max-retry-attempts: 3
  image:
    max-file-size: 10MB
    allowed-types: image/jpeg,image/png,image/jpg
  pagination:
    default-size: 20
    max-size: 100